### ISSUE TITLE
Don't silently destroy data

### ISSUE THREAD

**Issue by Llammissar** [jpillora/csv-to-influxdb#15]
I had a bunch of post-hoc data that I wanted to insert alongside my live data.  Insertion went well (after I applied the patches in PR #12), but I really, _really_ didn't expect this tool to clobber everything else in that database by default.  That really sucks.

Clearing an existing database _should_ be an _option_, sure, but it shouldn't be on by default.  And even then, it should also confirm the operation unless you've added a flag to force the issue.

**Comment by jpillora** [comment]
Ooo this sounds like a bad bug. So all prior data was deleted? It should
only issue a create db command when it's not found, and create db shouldn't
delete the existing db anyway...

**Comment by Llammissar** [comment]
Ugh, Mondays are especially bad when they come on a Tuesday!  Turns out my influx config was wrong, so they actually ended up in two separate databases.  Trying again with the correct target, it worked as expected.  Sorry for the scare!

**Comment by jpillora** [comment]
Ah phew
