### ISSUE TITLE
zsh: command not found: csv-to-influxdb

### ISSUE THREAD

**Issue by prakharmathur82** [jpillora/csv-to-influxdb#19]
I am trying to run this in mac, is it not available?

**Comment by cihanucar** [comment]
@prakhar345 I use zsh on mac and csv-to-influxdb works well:

![image](https://user-images.githubusercontent.com/1849101/27650863-2ce1cff6-5beb-11e7-9278-110796f643c9.png)

**Comment by jpillora** [comment]
See https://github.com/jpillora/csv-to-influxdb/releases/latest, the mac binary is `csv-to-influxdb_darwin_amd64.gz` (https://en.wikipedia.org/wiki/Darwin_(operating_system) )
