### ISSUE TITLE
timestamp format not working

### ISSUE THREAD

**Issue by jrblanno** [jpillora/csv-to-influxdb#21]
HI guys! 

I haven't been able to use the timestamp format properly. 
it  doesn't matter how I set the -tf parameter, the data on influxDB gets loaded with the import date, not whatever is in the timestamp column.

my file: testCSV

`timestamp,XMR_USD,XMR_BTC,BTC_MXN,XMR_DAY,XMR_MONTH,ROI,MXN_MONTH
2017-6-30 09:48:00,44.26477400,0.01784895,45414.00,0.1504,4.512,475.749,3657.39`

`./csv-to-influxdb -ts timestamp testCSSV`
in INFLUXDB 

`influx
Connected to http://localhost:8086 version 1.2.4
InfluxDB shell version: 1.2.4
> use test
Using database test
> select * from data
name: data
time                BTC_MXN MXN_MONTH ROI     XMR_BTC    XMR_DAY XMR_MONTH XMR_USD   timestamp
----                ------- --------- ---     -------    ------- --------- -------   ---------
1500916990119372139 45414   3657.39   475.749 0.01784895 0.1504  4.512     44.264774 2017-6-30 09:48:00`

How should I use the -tf option correctly ?

**Comment by syfantid** [comment]
Same problem here. After the insertion I have a new column time, which includes the import timestamp. In other words time column is treated as a timestamp and timestamp column is treated as a simple field. Any workaround? 
Running this line created the aforementioned behavior:
`.\csv-to-influxdb_windows_amd64.exe -d test1 -m level -t location -ts timestamp test1.csv`
Changing the name of the timestamp column to time in the CSV file and running the line below:
`.\csv-to-influxdb_windows_amd64.exe -d test2 -m level -t location -ts time test1.csv`
Produced the error:
`Timestamp column (time) does not match any header ()`
