### ISSUE TITLE
Timestamp formatting

### ISSUE THREAD

**Issue by hminnnn** [jpillora/csv-to-influxdb#24]
Hi,
Is it possible if i want to use my id column as the timestamp column instead of having a real timestamp like 2006-01-02 15:04:05 included in my csv file? How should i specify the format of my new "timestamp records" for the -tf if it is a number instead of the default timestamp's format?
eg. 
id,level,victor
1,1,2
2,3,4
3,5,6

**Comment by safdarrizvi** [comment]
You should have to pass TIMESTAMP column while inserting the data into InfluxDB as this is Time Series Database.
