### ISSUE TITLE
 Write failed: {"error":"partial write: field type conflict: input field \"value\" on measurement \"TCP_Connections\" is type string, already exists as type integer

### ISSUE THREAD

**Issue by jlancasterhmma** [jpillora/csv-to-influxdb#36]
Im recieving the following error when I try to import.
How can I specify what type the column is in my csv file?

 Write failed: {"error":"partial write: field type conflict: input field \"value\" on measurement \"TCP_Connections\" is type string, already exists as type integer

The field value is an integer in the TCP_Connections measurement in Influx.

My csv looks like below
time,host,value,description,port
1544470780000000000,"MES-A1-TDM-SVR-V",90,"Open_Protocol","4545"

Import command as follows:

/home/mesadmin/csv-to-influxdb -d telegraf --username "redacted" --password "redacted" -m TCP_Connections -t host --timestamp-column time --timestamp-format unix import.csv

**Comment by jlancasterhmma** [comment]
Sorry I had a row with an empty in that field.
Removed it and it fixed the issue. Sorry

**Comment by cnoork** [comment]
I had the same error but it was in my case a negative number which generated the error. For troubleshooting it would be nice to get also the line which causes the error. This will speedup troubleshooting.
